### ISSUE TITLE
Submission gets stuck on page 4; dependencies installation required

### ISSUE THREAD

**Issue by tmrozewski-york** [pkp/plagiarism#21]
This is distinct from Issue #13 but behaved the same way. It looks like my IT person found a fix locally.

Running OJS 3.3.0.8 and this plugin v1.0.5.0, new submissions were getting stuck on the Confirmation page. The log said:

`PHP Fatal error:  require_once(): Failed opening required '/var/www/refuge.journals.yorku.ca/ojs/plugins/generic/plagiarism/vendor/autoload.php'
`

If I deactivated the plugin, the submissions went through. My IT support used the composer to install dependencies manually, and now the plugin works and submissions are going through again. He wanted me to pass on the following message:

> Please ask Alec to update the installation instruction for the plugin to include the command to install the dependencies below as part of the installation
> 
> composer --working-dir=plagiarism install

**Comment by asmecher** [comment]
@tmrozewski-york, how did you install the plugin?

**Comment by tmrozewski-york** [comment]
@asmecher via the Plugin Gallery.

**Comment by ewhanson** [comment]
Thanks @tmrozewski-york, the issue's been fixed in the new release: https://github.com/pkp/plagiarism/releases/tag/v1_0_5-1. I'll post here once it's available via the Plugin Gallery.

**Comment by asmecher** [comment]
Thanks for reporting, @tmrozewski-york, and thanks for repackaging the plugin, @ewhanson! Please drop a note here if you have further trouble with it.
