### ISSUE TITLE
Cleanup error handling

### ISSUE THREAD

**Issue by ctgraham** [pkp/plagiarism#23]
### Too much logging

The plugin dumps attempts at sending files to the error log:

https://github.com/pkp/plagiarism/blob/f9e719852b6d3758df7a0e8eb46f226790e9133c/PlagiarismPlugin.inc.php#L110

This should be wrapped in a conditional (dependent on a setting?) or removed entirely.

[Edit: Removed with 62b95a9. - AS]

### Invisible logging

The plugin dumps errors of interest to a user to the error log:

https://github.com/pkp/plagiarism/blob/f9e719852b6d3758df7a0e8eb46f226790e9133c/PlagiarismPlugin.inc.php#L85
https://github.com/pkp/plagiarism/blob/f9e719852b6d3758df7a0e8eb46f226790e9133c/PlagiarismPlugin.inc.php#L98
https://github.com/pkp/plagiarism/blob/f9e719852b6d3758df7a0e8eb46f226790e9133c/PlagiarismPlugin.inc.php#L119

These errors should be of interest to an editor or admin, and should be reported as a notification.

**Comment by ctgraham** [comment]
Per https://github.com/pkp/plagiarism/pull/31#discussion_r909655494, remaining task is:
>  I think a trivial notification probably isn't a good fit. It'll cause a toast notification that will go away, possibly before it can be read/digested, and there's no way to get it back.

**Comment by ctgraham** [comment]
@wopsononock, for the current "trivial" / "toast" notifications and for any `error_logs()` on which a Journal Manager could take action, please convert these to Tasks which link to the submission / setting of interest.

**Comment by asmecher** [comment]
Closing; this has been implemented in recent betas, e.g. https://github.com/touhidurabir/pkp-plagiarism/releases/tag/1.0.7-0-Beta-7 for OJS/OMP/OPS 3.3.0-x. This will move into the Plugin Gallery as a formal release soon.
