### ISSUE TITLE
fatal error if unable to submit to iThenticate

### ISSUE THREAD

**Issue by jnugent** [pkp/plagiarism#25]
If for some reason the plugin fails to submit to iThenticate, the error_log call generates a fatal error because it tries to call getFilePath on a SubmissionFile which doesn't exist:

https://github.com/pkp/plagiarism/blob/master/PlagiarismPlugin.inc.php#L121

PHP Fatal error:  Uncaught Error: Call to undefined method SubmissionFile::getFilePath() in /var/home/ieee-ojs/latamt.ieeer9.org/www/plugins/generic/plagiarism/PlagiarismPlugin.inc.php:119

(the line numbers are slightly off because the error I'm including comes from the 3.3 version of the plugin)

This causes the final step of the submission process to hang.

Seen in 3.3.0.8

**Comment by asmecher** [comment]
Already fixed by 238daadabc4af031ff93efab88669b47aef18aa1.
