### ISSUE TITLE
Non-static method PKPApplication::getRequest() cannot be called statically

### ISSUE THREAD

**Issue by hktang** [pkp/plagiarism#32]
Hello, I noticed the plagiarism plugin is preventing submission on PHP8. It should be the same issue as https://github.com/pkp/customHeader/commit/0839e1d9d2dacf049147cc3ad9b29df0b06517eb. I wonder if this is fixed in a new version?

    Uncaught Error: Non-static method PKPApplication::getRequest() cannot be called statically in 
    /var/www/ojs/plugins/generic/plagiarism/PlagiarismPlugin.inc.php:65

Thanks in advance for fixing this.

**Comment by asmecher** [comment]
@hktang, what version of OJS are you using, and what version of the plagiarism plugin? (Please include this information with bug reports.)

**Comment by hktang** [comment]
Hi, I'm using the latest stable-3_3_0 branch of OJS. 

The plagiarism plugin is at 1.0.5.1 according to the version.xml file.

Hope this helps. And thanks for the reminder about including version numbers.

**Comment by asmecher** [comment]
Thanks, @hktang -- the fix is trivial; you can apply https://github.com/pkp/plagiarism/commit/7c3986c6587898e015aa3e36270b96399d290605. We'll include this in the next release.
