### ISSUE TITLE
New Submissions Confirmation is Failed

### ISSUE THREAD

**Issue by wpjianzhan** [pkp/plagiarism#46]
I Installed [plagiarism](https://github.com/pkp/plagiarism) to my ojs3.3.0.14，when I Submit an Article is Failed。
Beacuse，in PlagiarismPlugin.inc.php line 153，used Services::get('submissionFile')->getMany(...)，but submissionFile is not define（detail in classes/services/OJSServiceProvider.inc.php line 42）,
so update code to Services::get('submission')->getMany(...) can submit article success.

**Comment by jonasraoni** [comment]
Hi @Maxzhouup, could you please double check if everything is fine with your installation?

If you're using OJS 3.3.0-14, you should have these lines:
https://github.com/pkp/ojs/blob/313ada3804caa82754a434038324127e166f4552/classes/services/OJSServiceProvider.inc.php#L99-L102
