### ISSUE TITLE
PNG in supplemental files causes entire submission process to hang when plugin activated

### ISSUE THREAD

**Issue by tmrozewski-york** [pkp/plagiarism#48]
OJS 3.3.0.14
plugin 1.0.5.1

The editor of a journal using the iThenticate plugin emailed me to say that an author's submission is getting hung up at stage 4 (Confirmation) - when the author clicks "Finish Submission," the site hangs indefinitely. I replicated the problem with the same submission files - the behaviour is consistent with attempting to use an older version of the plugin or if the iThenticate credentials were changed but not updated in the plugin. My IT support shared the following error message with me:
`[Mon Jul 17 14:54:15.468991 2023] [php7:error] [pid 563741] [client 99.230.224.203:53149] PHP Fatal error:  Uncaught Error: Call to undefined method SubmissionFile::getFilePath() in /var/www/refuge.journals.yorku.ca/ojs/plugins/generic/plagiarism/PlagiarismPlugin.inc.php:119`

Turns out the problem was due to the inclusion of a PNG file, which I guess iThenticate can't handle. I could complete the submission as long as I removed the PNG file; if I included the PNG with the other files or uploaded it on its own, the process hung up. If I disabled the plugin, I was able to submit the PNG file.

It might help to prevent OJS from uploaded non-permitted filetypes to iThenticate, rather than having editors troubleshoot and toggle the plugin on a submission-by-submission basis.

**Comment by jonasraoni** [comment]
I didn't try to reproduce, but regardless of what file type iThenticate supports, that's an error that shouldn't happen.

There's a discussion here about how the file uploads should be implemented, so it probably won't be covered by this issue: https://github.com/pkp/plagiarism/discussions/33

**Comment by asmecher** [comment]
Closing; this has been implemented in recent betas, e.g. https://github.com/touhidurabir/pkp-plagiarism/releases/tag/1.0.7-0-Beta-7 for OJS/OMP/OPS 3.3.0-x. This will move into the Plugin Gallery as a formal release soon.
