### ISSUE TITLE
Enabling the plugin impossible if settings are present in config file when plugin is first installed

### ISSUE THREAD

**Issue by jnugent** [pkp/plagiarism#49]
This is  bit of a weird one.  We recently installed the plugin from the plugin gallery and then immediately added the relevant bits to  the config.inc.php file, and set the ithenticate = On setting there, plus the username and the password.

This has the effect of filling in the "enabled" check box in the plugins grid, and greying it out since the settings are present in the config file.  However doing it this way does not actually create the "enabled" setting in the plugin_settings table and the plugin will not run because of this.  Further, since the checkbox in the plugins grid is permanently checked/greyed out, it's not possible to truly enable the plugin.  It appears enabled but is in fact not.

The solution was to temporarily remove the config.inc.php settings, enable the plugin via the plugins grid, and then put the settings back in the config file.

**Comment by ctgraham** [comment]
So something is looking directly at the plugin settings table and not calling the plugin's `getEnabled()` method?  Do you happen to have a call stack for the guilty query?

**Comment by jnugent** [comment]
I do not.  The plugin "looks" like it's enabled, but it isn't.  I suspect what's happening is the getEnabled() method in the plugin gets called when the plugin grid is loaded:

https://github.com/pkp/plagiarism/blob/main/PlagiarismPlugin.inc.php#L61

And the second part of that returns true because the configuration settings are in the file.  That makes the plugin look enabled.  

I am not sure if the same code runs when the plugin registry looks for plugins to hook against though.

**Comment by asmecher** [comment]
Closing; this has been implemented in recent betas, e.g. https://github.com/touhidurabir/pkp-plagiarism/releases/tag/1.0.7-0-Beta-7 for OJS/OMP/OPS 3.3.0-x. This will move into the Plugin Gallery as a formal release soon.
