### ISSUE TITLE
OJS 3.4 support

### ISSUE THREAD

**Issue by mariuszsienkiewicz** [pkp/plagiarism#50]
I believe it's a good time to introduce support for OJS 3.4; the required changes in this plugin are relatively straightforward. Do you have an estimated timeline for when support for this system version might be implemented?

I don't know your specific development plans. It's possible that you're considering the addition of new features, which could explain the delay in supporting OJS 3.4. However, if you're aiming for a more straightforward approach, I'd like to inform you that I've already ensured compatibility with OJS 3.4 for my client. If it aligns with your goals, I'm prepared to submit a PR to hopefully make the official support process faster.

**PR**
https://github.com/pkp/plagiarism/pull/54

**Comment by asmecher** [comment]
Hi @mariuszsienkiewicz! The short answer is that it slipped my notice -- my apologies! I'd be very happy to review a PR, merge, and build a new release of the plugin. Thanks for offering.

**Comment by touhidurabir** [comment]
@asmecher can you please review the PR at https://github.com/pkp/plagiarism/pull/53

**Comment by touhidurabir** [comment]
@asmecher please review the PR at https://github.com/pkp/plagiarism/issues/50#issue-1895030856 which is based on initial PR by the author .
