### ISSUE TITLE
iThenticate v2 (CrossRef similarity check) support

### ISSUE THREAD

**Issue by gljk** [pkp/plagiarism#52]
My journal has recently got similarity check through CrossRef and the credentials we use for login to turnitin at our unique link https://crossref-[your member ID].turnitin.com  do not seem to work with this plugin. 

https://www.crossref.org/documentation/similarity-check/ithenticatev2-account-setup/

We have not been able to get the plugin working with iThenticate v2.

**Comment by touhidurabir** [comment]
@asmecher please review the PR at https://github.com/pkp/plagiarism/pull/57

**Comment by touhidurabir** [comment]
@asmecher PR has been updated as per requested changes. If all ok, I can start working porting these changes to `stable-3.4.0` and `main` .

**Comment by touhidurabir** [comment]
@asmecher PR updated based on new EULA requirement and some good enhancement . see more details about the implementation details at https://github.com/pkp/plagiarism/pull/57#issue-2120462053 . Please review the PR again .

**Comment by touhidurabir** [comment]
@asmecher please review the PR at https://github.com/pkp/plagiarism/pull/57 . Done adding the similarity scores, retrying, polling and viewer launch functionality .

**Comment by asmecher** [comment]
@touhidurabir, I added a note about a fatal error on saving the settings form in the beta plugin: https://github.com/touhidurabir/pkp-plagiarism/commit/a6fa2b89e49de352c51387fff4d5d710df58e9af#r145194028

**Comment by touhidurabir** [comment]
@asmecher can you review the commit [added revision files history feature](https://github.com/touhidurabir/pkp-plagiarism/commit/0b3fcd636aa5ddc6af65b894bd218871cd63658c) that add the ability to resent the revision files along with contains previous files plagiarism check history

**Comment by asmecher** [comment]
@touhidurabir, I see the code to track the history, but it doesn't look like there's an indication yet to the editor when the file has been revised since the plagiarism check was performed.

**Comment by touhidurabir** [comment]
Resolved by PR https://github.com/pkp/plagiarism/pull/57
