### ISSUE TITLE
Add iThenticate plugin support for OPS

### ISSUE THREAD

**Issue by asmecher** [pkp/plagiarism#55]

**Comment by Ppantaleo** [comment]
Hi Alec, I was wondering about the usefulness of iThenticate for a preprint. I look forward to implementing it when the plugin is ready.

**Comment by asmecher** [comment]
@Ppantaleo, we will be adding support for OPS, but only once some mix of the following have been implemented:
- https://github.com/pkp/plagiarism/issues/12
- https://github.com/pkp/plagiarism/issues/4

Otherwise the higher volume of submissions that preprint servers can experience might make the use of iThenticate very expensive for the host. That work is underway (along with https://github.com/pkp/plagiarism/issues/52) so watch those issues for progress.

**Comment by asmecher** [comment]
Closing; this has been implemented in recent betas, e.g. https://github.com/touhidurabir/pkp-plagiarism/releases/tag/1.0.7-0-Beta-7 for OJS/OMP/OPS 3.3.0-x. This will move into the Plugin Gallery as a formal release soon.
