### ISSUE TITLE
OJS 3.4 support

### ISSUE THREAD

**Issue by temin** [pkp/plagiarism#59]
If I understood the issue #50 correctly, the plugin code should now support OJS 3.4, but according to data in plugin-gallery, the newest version of plugin only supports OJS 3.3.x.

**Comment by asmecher** [comment]
@temin, we are currently updating the API that the plugin uses to a newer iThenticate API; after that work is completed, it'll be ported forward to 3.4.0 and fresh copies of the plugin will be released.

**Comment by temin** [comment]
Thanks @asmecher
Will wait then for new release.
