### ISSUE TITLE
multiple journal support

### ISSUE THREAD

**Issue by eddoff** [pkp/plagiarism#8]
We have many journals in the same OJS-server. We want to have the ability to set separate login credentials for different journals. For example in config.inc.php usernames and passwords could be added analogous to the base_url variable.

```
username = "default-login@eee.ff"
password = "qqqqq"

username[journal1] = "ddd@eee.ff"
password[journal1] = "xxxx"

username[journal2] = "aaa@bbb.cc"
password[journal2] = "yyy"
```

**Comment by jmvezic** [comment]
Same here. This plugin is currently only possible with multijournal installations if they're all using the same credentials (which sometimes isn't the case). @asmecher would it be possible to leave the config.inc.php option for all journals, but also allow journal-level "override" as a plugin setting?

**Comment by aguen** [comment]
Same for me. We would like to use this plugin - but in a multi-journal installation we can't because we do not want to give journal editors access to submissions from other journals.

**Comment by asmecher** [comment]
> would it be possible to leave the config.inc.php option for all journals, but also allow journal-level "override" as a plugin setting?

Yes, that would be a good solution; we've used that approach for other plugins/configuration items.

**Comment by mijzinga** [comment]
That would be great! We are also interested to have the ability to set separate login credentials for different journals. Much appreciated. Do you think it will be assigned to someone?

**Comment by asmecher** [comment]
The dev team is pretty swamped with work on OJS/OMP/OPS 3.4 until that's out -- but I do not some interest in improvements to this plugin from the community, and as always, we're open to pull requests!

**Comment by devsoper** [comment]
Just chiming in to say that we would greatly appreciate the ability to use separate Similarity Check / iThenticate credentials. Our journals run in a consortia-hosted, multi-tenant install of OJS, so we can't really use the plugin at present because one institution's Crossref account would need to be used for journals based at a variety of different institutions. Hopefully you can find some time to work on this after the 3.4 release, Alec!

**Comment by asmecher** [comment]
PR: https://github.com/pkp/plagiarism/pull/24

**Comment by asmecher** [comment]
The implementation in this issue augments the configuration file with journal-specific options; note that there's a separate request for web-based configuration, over here: https://github.com/pkp/plagiarism/issues/28
